# Generated by Django 5.1.3 on 2024-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='player_count',
            field=models.IntegerField(default=0, verbose_name='Players Count'),
        ),
    ]
